on:
  push:
     branches:
       - master

  

name: renderbook

jobs:
  bookdown:
    name: Render-Book
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("rmarkdown","bookdown"))'
      - name: Crete Dir
        run: mkdir -p _book      
      - name: Render Book
        run: Rscript -e 'bookdown::render_book("README.md")'
      - uses: actions/upload-artifact@v4
        with:
          name: _book
          path: _book/


  # Deployment job
  deploy:
   runs-on: ubuntu-latest
   needs: bookdown
   steps:
     - name: Checkout
       uses: actions/checkout@master
     - name: Download artifact
       uses: actions/download-artifact@v1.0.0
       with:
         name: _book 
         path: _book/
     - run: zip -r _book.zip _site/	
     - uses: ncipollo/release-action@v1	 
     - name: Deploy to GitHub Pages
       id: deployment
       uses: actions/deploy-pages@v4
